#! /usr/bin/env python2
# -.- coding: utf-8 -.-

import locale
import gettext
import signal
import sys
import os

locale_domain = "simply-ubuntu"

try:
    locale.setlocale(locale.LC_ALL, '')
except:
    pass
gettext.bindtextdomain(locale_domain, 'po')
gettext.textdomain(locale_domain)
gettext.install(locale_domain, 'po')

from simplyubuntu.app import SimplyUbuntuApplication

def get_data_dir():
    if os.path.isdir('/usr/share/simply-ubuntu'):
        return '/usr/share/simply-ubuntu/'
    else:         
        return os.getcwd()+'/data/'

if __name__ == '__main__':
    app = SimplyUbuntuApplication(get_data_dir())   
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    sys.exit(app.run(sys.argv))

